version: '3'

services:
  main_app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      - database

  database:
    image: sqlite:latest
    volumes:
      - ./database.db:/app/database.db
